### ISSUE TITLE
工作台：页面切换其实也支持缓存，只是加了过度效果，看起来像是重新渲染了，这个示例好像不起作用

### ISSUE THREAD

**Issue by xianyuwz** [jekip/naive-ui-admin#100]
工作台：页面切换其实也支持缓存，只是加了过度效果，看起来像是重新渲染了，这个示例好像不起作用

**Comment by jekip** [comment]
这是因为在重构 setup script 语法的时候，页面 name 丢失了，在页面补上缓存即可生效

**Comment by xianyuwz** [comment]
大佬，请问是在哪个地方补？路由上吗？

**Comment by jekip** [comment]
在页面写上
 `<script lang="ts">
  export default {
    name: 'BasicForm'
  }
</script>`
必须和路由定义的 `name` 保持一致，即可生效
