### ISSUE TITLE
It is recommended that the sidebar display should be modal on the mobile side 

### ISSUE THREAD

**Issue by MaybeQHL** [jekip/naive-ui-admin#101]
![image](https://user-images.githubusercontent.com/34638673/155089910-98faea0c-608e-4e90-9806-f941f7459e6f.png)
same this.

**Comment by MaybeQHL** [comment]
It prevents elements from being squeezed

**Comment by jekip** [comment]
Are you interested in supporting this feature？
We are mainly working on the 2.x version

**Comment by MaybeQHL** [comment]
Yeah.

**Comment by MaybeQHL** [comment]
Finished
