### ISSUE TITLE
深色主题导航栏高亮背景色与主题颜色不同步

### ISSUE THREAD

**Issue by Jervisol** [jekip/naive-ui-admin#103]
<img width="491" alt="微信图片_20220228152706" src="https://user-images.githubusercontent.com/38068957/155942356-55e34e43-6bf2-4533-bd33-8d0763a80920.png">
如图，标记处的背景颜色不会随主题颜色变化

**Comment by 851091009** [comment]
你好，请问解决了吗？

**Comment by jekip** [comment]
配置主题变量 `common.primaryColorSuppl`

**Comment by 851091009** [comment]
非常感谢！！！
