### ISSUE TITLE
GridItem各size对应窗口的尺寸分别是多少呢

### ISSUE THREAD

**Issue by Qujh97** [jekip/naive-ui-admin#104]
![image](https://user-images.githubusercontent.com/33251372/156476166-bab894f6-0b50-461c-9aea-605f3bb4220f.png)
如图，他们分别对应多少px，在文档中没有找到说明

**Comment by jekip** [comment]
文档有的，只是你没找到而已
`{ xs: 0, s: 640, m: 1024, l: 1280, xl: 1536, xxl: 1920 }`
