### ISSUE TITLE
点击登陆就会产生「 [Vue Router warn]: No match found for location with path "/dashboard" 」

### ISSUE THREAD

**Issue by xiaoxunyao** [jekip/naive-ui-admin#109]
<img width="1112" alt="Screen Shot 2022-03-10 at 7 53 23 PM" src="https://user-images.githubusercontent.com/43719490/157656652-6cb95266-81d7-446a-9a65-3c36ad13575d.png">

**Comment by jekip** [comment]
https://github.com/jekip/naive-ui-admin/issues/56#issuecomment-927206107

**Comment by xiaoxunyao** [comment]
可是并没有跳转，只显示这个报错

**Comment by jekip** [comment]
这个要你自行定位一下问题所在，演示项目，不会出现这种情况
尝试排查原因：
1、确保入口路由和页面都是存在的，`src\enums\pageEnum.ts` 这里面是页面相关配置
2、并没有跳转，具体是哪一步中断了，可以尝试跟踪一下代码执行过程
3、你这种情况，是对接了后端真实 `api` 地址出现的，还是说，你 `clone`下来没有改动什么，使用项目本身`mock`出现的

**Comment by xiaoxunyao** [comment]
1. 我并没有修改页面和路由的配置，
2. 我只是单纯的将获取用户信息的「admin_info」这个请求转为了真实的API请求

**Comment by jekip** [comment]
问题可能就在这里了，这个接口严格要求数据结构，如果你改变了接口，相应的代码也需要联动修改

**Comment by xiaoxunyao** [comment]
原来如此

**Comment by xiaoxunyao** [comment]
感谢您的答复呀
