### ISSUE TITLE
使用keepAlive后，再入时 query丢失，取不到参数

### ISSUE THREAD

**Issue by sootma** [jekip/naive-ui-admin#113]
使用keepAlive后，再入时 query丢失，取不到参数
router.beforeEach(async (to, from, next) => {
console.log("===== query: " + JSON.stringify(to.query));
})

**Comment by jekip** [comment]
1.x 多标签跳转存在问题， `query`  `params` 都存在问题，普通页面带参数页面，可能也存在

**Comment by sootma** [comment]
请问一下，这个问题有没有解决的时间表？还是说只能升到v2才能解决？

**Comment by jekip** [comment]
v2 多标签重构了，没法直接无缝对着改，没有具体时间，现在主力在维护 v2 版本，目前有四个生态要维护

**Comment by jekip** [comment]
1.8.0 已 fix
