### ISSUE TITLE
自己扩展的views刷新后白屏无内容

### ISSUE THREAD

**Issue by bobolike123** [jekip/naive-ui-admin#115]
自己扩展了views界面，但是点击刷新或者点击菜单别的项目再点回来会发生白屏，需要刷新浏览器初始化才能正常显示，但是内置的views没有这个问题，请问是需要配置什么参数吗
![xxx](https://user-images.githubusercontent.com/29175881/161422049-c18f7443-a15d-421f-8ee4-4d1678f93987.png)
![yyy](https://user-images.githubusercontent.com/29175881/161422052-ce64d359-c13a-4404-b68f-d9f0a3678e91.png)

**Comment by jekip** [comment]
页面不能存在多个，根标签，因为动画组件的原因
