### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html"

### ISSUE THREAD

**Issue by chpinck** [jekip/naive-ui-admin#118]
# 进入首页提示这个错误
- chrome
- Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by jekip** [comment]
删除废弃文件 `public/index.html` 重新运行即可

**Comment by chpinck** [comment]
确实如此，3Q
