### ISSUE TITLE
useForm中的setFieldsValue方法

### ISSUE THREAD

**Issue by samzhang1029** [jekip/naive-ui-admin#119]
我有一个Select组件,其中的option属性需要通过接口获取数据后再进行渲染,尝试使用setFieldsValue方法,但是不知道具体写法

**Comment by samzhang1029** [comment]
将schemas设置为ref可以解决

**Comment by jekip** [comment]
`setFieldsValue` 没暴露 ，需要通过 `const [register, { setFieldsValue }] = useForm()` 使用
