### ISSUE TITLE
锁屏不能用，点击了之后一片空白！

### ISSUE THREAD

**Issue by mx4g** [jekip/naive-ui-admin#120]
你好，锁屏不能用，点击了之后一片空白！ 再一次重新进去之后，都一片空白，回不去原来的首页了！
![image](https://user-images.githubusercontent.com/7499986/165253795-3232e34a-8a9e-494c-abbc-7d03e7531e41.png)

**Comment by jekip** [comment]
请用谷歌浏览器试试

**Comment by likailun101929** [comment]
谷歌浏览器  遇到同样问题  请问解决了？
