### ISSUE TITLE
不明白细粒权限相关问题 ?

### ISSUE THREAD

**Issue by a15218378694** [jekip/naive-ui-admin#121]
![image](https://user-images.githubusercontent.com/29919045/167352386-b03be01f-75c8-4e41-a787-1fc816363232.png)
这里为什么返回了跟权限无关的值 ?
以及文档里面, 这么写是字符串了
![image](https://user-images.githubusercontent.com/29919045/167352500-c15ace1c-2820-4bbe-b374-1761fcacd33a.png)

**Comment by jekip** [comment]
可以理解成，除了菜单/路由权限之外的权限，比如，页面删除/编辑按钮，特定功能操作按钮，等等权限，可以通过这个指令来处理

文档是随便写的权限名称，指令本身就是接收字符串数组，没有问题

**Comment by a15218378694** [comment]
应该是要拿roleEnum.ts文件里面的值吧

**Comment by a15218378694** [comment]
> 


应该是要拿roleEnum.ts文件里面的值吧

**Comment by jekip** [comment]
不是
