### ISSUE TITLE
在Table组件单独的columns.ts文件里使用router跳转，控制台会打印报错信息（能跳转）

### ISSUE THREAD

**Issue by Mrqqqwww** [jekip/naive-ui-admin#140]
报错信息 ![image](https://user-images.githubusercontent.com/30919325/175199603-623d01cb-4f46-488c-8c8a-599c7e397882.png)
跳转函数
![image](https://user-images.githubusercontent.com/30919325/175199718-5f7ddf02-b2e3-4b7d-bf72-a99a907032e9.png)
在columns.ts文件里 引入 import router from '@/router';  而不是 useRouter(提示只能在setup里使用)

**Comment by jekip** [comment]
看着像是你使用方式错了 
 
 你应该 import { useRouter } from 'vue-router'
 
 const router = useRouter()
 
 router.push()
 
 使用场景，请参考 vue-router 文档

**Comment by Mrqqqwww** [comment]
> 看着像是你使用方式错了
> 
> 你应该 import { useRouter } from 'vue-router'
> 
> const router = useRouter()
> 
> router.push()
> 
> 使用场景，请参考 vue-router 文档

我是在columns.ts 的render函数使用的，如果使用 useRouter() 会报这个错 
![image](https://user-images.githubusercontent.com/30919325/175501415-05495e6d-e836-4a23-9622-bf75d1207fdd.png)

**Comment by Mrqqqwww** [comment]
或者我换个问法，Table组件因为column.ts文件和vue文件是分开的，我想在column.ts文件里实现一些操作，比如通过render函数实现跳转，接口加载数据等，要怎么实现。

**Comment by jekip** [comment]
那就换个方式，columns.ts 移到页面中去定义，这里也不是一定要，抽离成一个单独的文件，当 columns 和页面存在依赖或者逻辑的时候，就不适应了

column 使用 render 函数获取数据，当然是没有问题，路由跳转 可能不太合适，或者 用原生 js 跳转

**Comment by Mrqqqwww** [comment]
> 那就换个方式，columns.ts 移到页面中去定义，这里也不是一定要，抽离成一个单独的文件，当 columns 和页面存在依赖或者逻辑的时候，就不适应了
> 
> column 使用 render 函数获取数据，当然是没有问题，路由跳转 可能不太合适，或者 用原生 js 跳转

好的，谢谢
