### ISSUE TITLE
如何去掉项目加载时请求的admin_info

### ISSUE THREAD

**Issue by mztlive** [jekip/naive-ui-admin#144]
![image](https://user-images.githubusercontent.com/13467892/176202625-8b9df3a3-ee6c-4786-b711-37e8f5b6739b.png)

如何去掉这该死的权限验证啊？ 我的项目不需要权限。

我改了Api地址的配置后进不去页面了

**Comment by jekip** [comment]
看一下 src\router\router-guards.ts 60 行左右逻辑，去掉权限，你可能需要改好几个地方，比如 router.beforeEach ，axios 请求拦截器
