### ISSUE TITLE
upload组件finish回调参数event.target问题

### ISSUE THREAD

**Issue by CrystalCoCo** [jekip/naive-ui-admin#148]
n-upload 的 onFinish 回调参数， {file, event} , 项目build之后或者本地运行yarn preview预览之后， 这个值是event.target是个null, 导致上传图片拿不到上传结果，但是本地localhost运行event.target是有值的

**Comment by mediolop** [comment]
线上需要关闭 mock 不然会影响

**Comment by jekip** [comment]
线上关闭 mock
