### ISSUE TITLE
关于判断路由下面的 children数量自动会变成嵌套的模式的修改建议

### ISSUE THREAD

**Issue by long5635152** [jekip/naive-ui-admin#150]
目前的情况是只要路由下面的 children数量大于1，就会变成嵌套模式；但是如果现在children有两个路由，其中一个将hidden设置为了true，这是也会变为嵌套模式，但实际展示在菜单中的还是一个页面，建议将判断改为children数量大于1并且hidden=true的数量不等于1

**Comment by jekip** [comment]
当只有一个子菜单的时候，嵌套路由， 会变成顶级路由，可以在 `mate` 里面把 这个参数 `alwaysShow`  设置成 `false`  关闭这个特性

**Comment by jekip** [comment]
`hidden` 参数没有考虑在内，可以自行补充一下，这个特性或许别人不想这样、

**Comment by long5635152** [comment]
我自己的项目已经改了，但是我建议把这个特性弄成一个meta参数，让使用者可以选择

**Comment by jekip** [comment]
可以，后续版本加上

**Comment by lzb-libra** [comment]
大神们，我有个问题，就是我有一个页面，想通过点击某个按钮跳转到某个页面A，但是这个页面A我不想显示到左侧的菜单栏中，我将该页面hidden设置为true时，会将我上级菜单的名称给隐藏掉，我要如何做才能做到页面不在左侧列表中又能通过router-link进行跳转到页面A

**Comment by lzb-libra** [comment]
@long5635152 请问你是怎么修改的那，我要是想要一个详情页面，这个页面不需要在菜单栏中显示，点击某个按钮后在跳转到详情页面

**Comment by long5635152** [comment]
@lzb-libra  @/utils/index/ts 里isRootRouter这个方法，改成如下：
`export function isRootRouter(item) {
  if((item.meta?.alwaysShow != true && item.children?.length === 1) || (item.meta?.alwaysShow != true && item.children?.length > 1 && item.children?.filter(v=> !v.meta.hidden).length === 1)) {
    return true
  } else {
    return false
  }
}`

**Comment by long5635152** [comment]
@lzb-libra @/utils/index/ts 里isRootRouter这个方法，改成如下：
`
export function isRootRouter(item) { 
  if((item.meta?.alwaysShow != true && item.children?.length === 1) || (item.meta?.alwaysShow != true && item.children?.length > 1 && item.children?.filter(v=> !v.meta.hidden).length === 1)) { 
  return true 
  } else {
   return false 
  } 
}
`
以前的逻辑是只判断alwaysShow和children的length，改了之后的逻辑其实就是增加了对hidden的判断

**Comment by lzb-libra** [comment]
@long5635152 多谢大神指点，我也感觉咱俩是一个问题，研究了半天，主要是chrome不能debugger，没找到头绪，Thanks♪(･ω･)ﾉ

**Comment by YuCarl77** [comment]
为什么判断`alwaysShow` 判断是 `!= true`呢, 如果要按根节点显示，不考虑隐藏的，那也应该是 `=== true && item.children?.length === 1`呀。
