### ISSUE TITLE
路由配置activeMenu的bug

### ISSUE THREAD

**Issue by long5635152** [jekip/naive-ui-admin#151]
子路由设置activeMenu后，点击进入子页面确实可以高亮对应菜单栏，但是如果在子页面中刷新，高亮就会消失，详见：
[列表页面-基础详情](https://naive-ui-admin.vercel.app/#/list/basic-info/604841)，直接打开后并没有高亮对应菜单

**Comment by jekip** [comment]
1.x 确实是bug，没有人pr的话，下个版本我看下修一下

**Comment by long5635152** [comment]
谢谢，已经修复了
