### ISSUE TITLE
TableAction爆出一个奇怪的错误

### ISSUE THREAD

**Issue by Lubin502831** [jekip/naive-ui-admin#160]
![image](https://user-images.githubusercontent.com/76585680/181602855-f890cf9d-ceb5-4a39-9d40-3ae5d59e0065.png)

![image](https://user-images.githubusercontent.com/76585680/181602799-87e2ee95-b540-4ce8-a539-682f7c9ac9a2.png)

**Comment by jekip** [comment]
设置 `BasicColumn` 类型即可
