### ISSUE TITLE
移动端模式tooltip显示问题

### ISSUE THREAD

**Issue by HnyLi** [jekip/naive-ui-admin#172]
在移动端模式下点击header部分的按钮会弹出tooltip，但是不会自动关闭，需要用户进行其他点击行为才会触发关闭，这时tooltip会覆盖在其他内容上
复现：f12进入移动端模式，选择iPad Air，点击header部分的项目配置图标
![image](https://user-images.githubusercontent.com/79054161/188043498-d79c3e01-987b-472d-89ef-5cabef7a82dd.png)

**Comment by jekip** [comment]
这是UI框架的问题，因为并不是定位移动端UI框架，这种移动端交互体验，框架很多组件或许都会有一些类似的问题出现
