### ISSUE TITLE
V1预览和文档站点无法访问

### ISSUE THREAD

**Issue by lostin21st** [jekip/naive-ui-admin#176]
站点：https://naive-ui-admin-docs.vercel.app/ 无法访问。
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/19514272/190121900-bd936043-d3ce-40b5-97d0-62725455575e.png">
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/19514272/190123443-7bcab574-2fc2-4640-b65b-0696fa1320a9.png">

**Comment by jekip** [comment]
备用地址：https://jekip.github.io/docs/
