### ISSUE TITLE
Table 组件 非受控排序失效

### ISSUE THREAD

**Issue by SK-ERIC** [jekip/naive-ui-admin#180]
问题：在 src\views\comp\table\basicColumns.ts 中使用排序，发现无效。更改如图：

![image](https://user-images.githubusercontent.com/52649359/192238998-23cac408-f75a-47a7-8907-f23dd7615ddf.png)；

navie-ui 非受控过滤 & 排序: [非受控使用文档](https://www.naiveui.com/zh-CN/os-theme/components/data-table#filter-and-sorter);

GIF 问题描述：
![动画](https://user-images.githubusercontent.com/52649359/192241338-00678075-ef44-4668-90d3-c15b5eadaa6c.gif)

**Comment by jekip** [comment]
可以自己加上 `@update:sorter` 方法逻辑

**Comment by SK-ERIC** [comment]
> 可以自己加上 `@update:sorter` 方法逻辑

ok，了解，**BasicTable** 组件默认设置了`remote: true`属性，如果使用服务端返回的数据进行展示，分页，过滤，排序等，请参考[异步](https://www.naiveui.com/zh-CN/os-theme/components/data-table#ajax-usage)。
