### ISSUE TITLE
BasicForm component 

### ISSUE THREAD

**Issue by RonLeeLi** [jekip/naive-ui-admin#181]
{
    field: 'regionId',

    component: 'NTreeSelect',  

    label: '所在区县',
    componentProps: {
      placeholder: '请选择所在区县',
      onUpdateValue: (e: any) => {
        console.log(e);
      },
    },
  },

component 组件都无法渲染，如何解决呢  比如级联组件  下拉树菜单

**Comment by jekip** [comment]
在 `/src/plugins/naive.ts`  导入 `NTreeSelect`
