### ISSUE TITLE
keep-alive 失效

### ISSUE THREAD

**Issue by TheBlindM** [jekip/naive-ui-admin#188]
onMounted 每次都会进入

**Comment by jekip** [comment]
在 `router` 中 `meta` 内将 `keepAlive` 设置为` true`
页面路由设置 `name`，且不能重复
页面加上 ` name`，与路由设置的 ` name` 保持一致

**Comment by jekip** [comment]
比如：
`<script lang="ts">
  export default {
    name: 'CaseLibrary'
  };
</script>
`
`name`  不要定义成中文

**Comment by hyingreborn** [comment]
请教一下作者 @jekip ，我看源码里路由中是以路由的name作为keepAlives中的，但keepAlive组件的include好像认的是组件的name
我是这样写才生效的：
```
# /src/router/router-guards.ts
const currentComName: any = to.matched.find((item) => item.name == to.name)?.components.default.name;
```

**Comment by jekip** [comment]
> 请教一下作者 @jekip ，我看源码里路由中是以路由的name作为keepAlives中的，但keepAlive组件的include好像认的是组件的name 我是这样写才生效的：
> 
> ```
> # /src/router/router-guards.ts
> const currentComName: any = to.matched.find((item) => item.name == to.name)?.components.default.name;
> ```

对的，路由 `name` 和 组件 `name` 必须一致才行，另外这个版本，只能缓存两级菜单，以上就不行了

**Comment by hyingreborn** [comment]
明白了，你这个相当于是约定了保持一致，传的是路由名，实际还是按照组件名来缓存的。我这样写好像就不限制路由名必须一致了。刚切到vue3，还得一点一点踩坑😂

**Comment by jekip** [comment]
示例已补充

**Comment by Kerwin1202** [comment]
clone 了项目 什么都没改 采用 yarn dev 运行之后 似乎无效
一个是看代码 有这个参数，然后打开工作台 输入 11111  切换 别的tab 切换回来 发现 11111 消失了

目的是想 原有的 输入框 或者 table 等组件不要重复加载

<img width="982" alt="image" src="https://github.com/jekip/naive-ui-admin/assets/16319833/ef11b82b-a29a-4052-9fb2-146b28cd9beb">
<img width="1031" alt="image" src="https://github.com/jekip/naive-ui-admin/assets/16319833/deeea5d3-661e-4ea3-8918-1d34bfa5ccf7">
