### ISSUE TITLE
项目报错，起不来

### ISSUE THREAD

**Issue by Erik5169** [jekip/naive-ui-admin#19]
install 后， 运行报错，无法启动
<img width="1049" alt="截屏2021-08-05 下午9 24 05" src="https://user-images.githubusercontent.com/25293699/128357438-2c8df9e7-87fd-4c28-b8fd-102d05e31f07.png">
<img width="1069" alt="截屏2021-08-05 下午9 24 13" src="https://user-images.githubusercontent.com/25293699/128357461-6997a7b5-f932-4dbe-a4bf-dd3bddc76d26.png">
<img width="1086" alt="截屏2021-08-05 下午9 24 22" src="https://user-images.githubusercontent.com/25293699/128357471-39b9f414-1b5f-49b4-9352-8bad5616cce9.png">

**Comment by jekip** [comment]
不好意思，文件少add了，已提交，重新pull一下

**Comment by Erik5169** [comment]
可以了，谢谢啦
