### ISSUE TITLE
BasicTable 性能有问题，数据一多就会卡

### ISSUE THREAD

**Issue by shi-sky** [jekip/naive-ui-admin#199]
BasicTable 性能有问题，数据一多就会卡
数据量100条 
  v-model:checked-row-keys="checkedData"
这个checkbox 勾选就会卡，同时编辑数据也会卡

**Comment by jekip** [comment]
大量数据性能的确不是很好，之前跟踪了一下，二次封装的代码执行时间是很快的，table 组件底层渲染反而慢了，没啥好的解决方案，可以到 `naiveui ` 仓库反馈一下
