### ISSUE TITLE
useForm钩子在basicModal中出现bug

### ISSUE THREAD

**Issue by tanwenchao** [jekip/naive-ui-admin#204]
在view/comp/modal/index.vue okModal方法中，
表单必填项已填写，但是const formRes = await submit()，formRes一直返回的undefined

**Comment by tanwenchao** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/17673324/206860067-3b3d0d16-6a29-4fdf-9bf3-e836c019398e.png">
在basicModal添加@submit="handleSubmit"。。

**Comment by yzlhdy** [comment]
解决了吗

**Comment by lenghuo** [comment]
> 解决了吗

在BasicForm添加@submit="handleSubmit"

在script里，新建handleSubmit方法
```javascript
// 如果前面验证通过的话，会自动执行这一步
const handleSubmit = (e: any) => {
// e就是要提交的表单数据
};
```

**Comment by jekip** [comment]
`1.9.0` 已优化
