### ISSUE TITLE
bug: 退出登录后，并未完全移除tab，页面携带参数无法匹配高亮

### ISSUE THREAD

**Issue by dockfries** [jekip/naive-ui-admin#208]
Header/index.vue
```ts
// 移除标签页
localStorage.removeItem(TABS_ROUTES); // 且存储用storage实例 这边却用原生localStorage 不规范
```
TagsView/index.vue
```ts
// 在页面关闭或刷新之前，保存数据
window.addEventListener('beforeunload', () => {
  storage.set(TABS_ROUTES, JSON.stringify(tabsList.value));
});
```

思路1: 登出时清空`useTabsViewStore`里的`tabList`,而不是进行`storage`的`removeItem`
思路2: 删除页面关闭刷新保存数据，而是在`useTabsViewStore`的`tabList`内部发生变化时进行存储

**Comment by YuCarl77** [comment]
另: `TagsView/index.vue`的`'active-item': activeKey === element.path`应该修改为`element.fullPath`，不然页面如果携带了query参数就无法匹配高亮了

**Comment by jekip** [comment]
> 另: `TagsView/index.vue`的`'active-item': activeKey === element.path`应该修改为`element.fullPath`，不然页面如果携带了`query`参数就无法匹配高亮了

确实存在

> 另: `TagsView/index.vue`的`'active-item': activeKey === element.path`应该修改为`element.fullPath`，不然页面如果携带了`query`参数就无法匹配高亮了

确实存在

**Comment by jekip** [comment]
`1.9.0` 已 `fix`
