### ISSUE TITLE
项目启动时报错

### ISSUE THREAD

**Issue by zhangcscc** [jekip/naive-ui-admin#223]
![image](https://user-images.githubusercontent.com/41695608/221459319-b4e6f588-5d0a-4f85-a5b1-f33353489ec1.png)

**Comment by zhangcscc** [comment]
我本的是node版本是：
![image](https://user-images.githubusercontent.com/41695608/221459810-d54ce1c4-092a-4d06-81dd-7a60a2240679.png)

**Comment by lzcdhub** [comment]
![image](https://user-images.githubusercontent.com/54580497/222062367-e072f4eb-6cf2-4fdc-99d9-8651e6181dcf.png)

**Comment by zhangcscc** [comment]
好的，我升级下node应该就可以了；我是看配置中 node version >= 14 都行；
![image](https://user-images.githubusercontent.com/41695608/222062917-3a4be5b2-5f90-44d7-b27c-bccf98ebb4aa.png)
