### ISSUE TITLE
项目偶尔白屏

### ISSUE THREAD

**Issue by Liruimin2** [jekip/naive-ui-admin#231]
![image](https://user-images.githubusercontent.com/30410070/230534828-cd28e5b4-7109-4f2b-8b2f-d0896f8d383c.png)

**Comment by jekip** [comment]
开发环境，热更新，有时候存在这个问题，`vite` 官方也有人提过，尝试 升级 `vite 4.x`  试试

或者你有存在一下的行为，https://github.com/jekip/naive-ui-admin/issues/183
