### ISSUE TITLE
表格组件，Tooltip bug? 

### ISSUE THREAD

**Issue by muyangsx** [jekip/naive-ui-admin#244]
如果表格单元格内，使用以下代码去渲染，即使内容超过表格允许的最大宽度，也不会成功的展示出 tooltip，是我设置的方式不对，还是存在bug?

render(record) {
      return h('div', { class: 'n-ellipsis' }, 'ID:' + record.id);
},

**Comment by jekip** [comment]
你自定义 `render` 了，是不是就不会触发 `tooltip` 效果了？
