### ISSUE TITLE
谷歌浏览器问题

### ISSUE THREAD

**Issue by loongzcode** [jekip/naive-ui-admin#247]
在谷歌浏览器打开开发者工具，侧边菜单栏会变成白色，
![image](https://github.com/jekip/naive-ui-admin/assets/55130487/9af284ce-c615-4541-a89a-c9bf98c19e82)

**Comment by jekip** [comment]
没有复现，可以提供详细一点信息吗

**Comment by davinma** [comment]
> 

我也复现了，缩小窗口宽度，当左边 sidebar 自动隐藏后，再点击左上角 `.layout-header-trigger` 里面的伸缩图标，就会出现 [loongzcode](https://github.com/loongzcode) 截图上的浮动抽屉，这个抽屉背景浅色的，和默认的左边 sidebar 深色背景不协调。

**Comment by jekip** [comment]
这个功能是社区小伙伴贡献的 `pr` 可以@他修一下

**Comment by jekip** [comment]
我修复了
