### ISSUE TITLE
FormSchema的NCascader

### ISSUE THREAD

**Issue by UFO233** [jekip/naive-ui-admin#248]
<img width="598" alt="image" src="https://github.com/jekip/naive-ui-admin/assets/29417751/a8e6f0ff-c205-4dd4-af17-6d12ee64cde7">
页面没渲染出来

**Comment by jekip** [comment]
你很有可能没有导入这个组件 `NCascader `

**Comment by UFO233** [comment]
我后来导入了，但是下拉数据没有渲染出来，如果写死就可以渲染出来发自我的 iPhone在 2023年7月21日，16:27，Ah jung ***@***.***> 写道：﻿
你很有可能没有导入这个组件 NCascader

**Comment by jekip** [comment]
`1.9.0` 已补充
