### ISSUE TITLE
设置中，顶部菜单混合模式无效（图1）,顶部菜单模式下， 界面显示无效，且样式有问题（图2）

### ISSUE THREAD

**Issue by vv-lin** [jekip/naive-ui-admin#25]
图1
![image](https://user-images.githubusercontent.com/44837766/129168647-7abbe73e-823c-4e4b-94d0-e111caf7448a.png)

图2
![image](https://user-images.githubusercontent.com/44837766/129169134-8379608e-4454-4bc5-b08d-5074560132b1.png)

**Comment by jekip** [comment]
图一：顶部混合菜单，需要再次点击分割菜单按钮，才会看到效果
图二：顶部菜单模式，为了解决横向空间，隐藏了重载按钮，以及面包屑导航，交互也确实没处理（这里期望是啥样的交互比较好）
样式：横向菜单这里当屏幕过小的时候，确实没有处理，因为这是UI库menu组件本身的效果，目前除了重写menu组件，没有更好的方法

**Comment by vv-lin** [comment]
> 图一：顶部混合菜单，需要再次点击分割菜单按钮，才会看到效果
> 图二：顶部菜单模式，为了节约横向空间，隐藏了重载按钮，以及面包屑导航，交互也确实没处理（您觉得这里什么的交互比较好）
> 样式：横向菜单这里当屏幕过小的时候，确实没有处理，因为这是UI库menu组件本身的效果，目前除了重写menu组件，没有更好的方法

非常感谢作者的认真回复，有一些个人的想法，不一定对，仅供参考。
图一：顶部混合菜单点击之后，建议是默认自动选中分割菜单。另外，分割菜单后不用显示两个logo，保留左上角的就好。
图二：在顶部混合菜单和顶部菜单模式下，右上角部分个人觉得可以缩减部分，比如只保留头像部分，其余内容放到头像的下拉中，做好分组会比较清晰。
其中比较麻烦的当属于全局搜索按钮，可以尝试点击全局搜索后在头像下拉位置加一个悬浮搜索框，类似谷歌浏览器的Ctrl + F出现的搜索框。
另外，由于示例项目中一级菜单较多，可以尝试加一个多页签类似的左右翻页功能（样式得稍微设计一下，不然会非常难看），作为补充。还可以尝试加一个去掉菜单图标显示的开关按钮，关闭后能稍微展示更多内容。
还有一个小细节，就是在小屏幕下文字显示不全，且菜单没有tip。

**Comment by jekip** [comment]
1、横向菜单，menu组件，官方ui库已经在考虑优化了
2、显示2个logo，这个是bug（近期会修复）
3、混合菜单和顶部菜单模式下，右上角部分这个其实得自己去考虑了，因为每个项目都不同，可能有些项目，只需要显示一个头像下拉组件，就好了
