### ISSUE TITLE
useModal+useForm组件的bug

### ISSUE THREAD

**Issue by zhoushi1** [jekip/naive-ui-admin#250]
"naive-ui": "^2.34.2"

#157 这里有提供解决方案，但不能完全解决。

useForm组件的submit方法，返回的是undefined。
想知道这是什么bug，我有一些逻辑需要写在判断里。

![image](https://github.com/jekip/naive-ui-admin/assets/44335231/cd3b5b5d-4bc0-448d-a36b-8d96a1a0d538)

**Comment by jekip** [comment]
弹窗套 `useForm` 组件，要确保加载顺序，你提供的代码片段，看不出问题在哪，你可以给 `form` 加上 `formRef` 试一下，如果不能拿到实例，就说明是存在加载顺序问题的

**Comment by zhoushi1** [comment]
官方的给的例子就有问题，拿官方的例子一样返回的undefined

**Comment by zhoushi1** [comment]
> 弹窗套 `useForm` 组件，要确保加载顺序，你提供的代码片段，看不出问题在哪，你可以给 `form` 加上 `formRef` 试一下，如果不能拿到实例，就说明是存在加载顺序问题的

官方的给的例子就有问题，拿官方的例子一样返回的undefined

**Comment by tanwenchao** [comment]
<img width="1680" alt="image" src="https://github.com/jekip/naive-ui-admin/assets/17673324/684a089b-924b-40ea-a6b4-0b6e72164120">

**Comment by tanwenchao** [comment]
也遇到了一样的问题，姓名已经填了，表单校验不能通过，submit方法一直返回undefined

**Comment by jekip** [comment]
`1.9.0` 已 `fix`

**Comment by tanwenchao** [comment]
... 1.9.0，大佬，现在不是2.34.2了吗😆

**Comment by GabbyMrH** [comment]
问题依然存在
