### ISSUE TITLE
TableAction组件，左右间隔不生效

### ISSUE THREAD

**Issue by zhoushi1** [jekip/naive-ui-admin#253]
如图所示，n-button按钮的左右margin会覆盖.mx-2中的左右margin

![image](https://github.com/jekip/naive-ui-admin/assets/44335231/104315a4-334c-4766-9aef-08324ae898bd)

**Comment by zhoushi1** [comment]
手动修复了，在TableAction组件中，增加了style样式！
![image](https://github.com/jekip/naive-ui-admin/assets/44335231/521e0d29-1a3b-49b8-b8d7-1d61d1882351)

**Comment by jekip** [comment]
样式权重问题，`1.9.0` 已 `fix`
