### ISSUE TITLE
BasicForm的一些问题

### ISSUE THREAD

**Issue by tanwenchao** [jekip/naive-ui-admin#256]

**Comment by tanwenchao** [comment]
{
      field: 'type',
      component: 'NSelect',
      label: '类型',
      componentProps: {
        placeholder: '请选择类型',
        options: [
          {
            label: '舒适性',
            value: 1,
          },
          {
            label: '经济性',
            value: 2,
          },
        ],
        onUpdateValue: (e: any) => {
          console.log(e);
        },
      },
      rules: [{ required: true, message: '请选择类型', trigger: ['blur'] }],
    },

下拉框为必填时，选择了选项，但是不能通过表单验证

**Comment by tanwenchao** [comment]
<img width="1161" alt="image" src="https://github.com/jekip/naive-ui-admin/assets/17673324/5595f525-f3a1-4d0c-905a-bbe11d90f785">

**Comment by macbooking** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/form

**Comment by macbooking** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/form

**Comment by macbooking** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/form 如果你需要为一个值为 number 类型的表项设定 required，你需要在 rule 对象中设定 `type: number`。

**Comment by jekip** [comment]
> https://www.naiveui.com/zh-CN/os-theme/components/form 如果你需要为一个值为 number 类型的表项设定 required，你需要在 rule 对象中设定 `type: number`。

非常 `nice` Thank
