### ISSUE TITLE
useFrom中setFieldsValue渲染顺序问题

### ISSUE THREAD

**Issue by TyCoding** [jekip/naive-ui-admin#258]
在子组件使用了useForm，并且定义了Init函数用于父组件调用显示model框
const [register, { setFieldsValue }] = useForm()
function init() {
    showModel = true
    setFieldsValue({}) //此时设置值无法用
}

<<Child ref='childRef'

当父组件使用childRef.init()时，无法为子组件的form设置值，请问这个情况该如何处理啊？

**Comment by jekip** [comment]
包裹 `nextTick`
