### ISSUE TITLE
为什么根据文档的代理配置还是无法代理？

### ISSUE THREAD

**Issue by 1604653069** [jekip/naive-ui-admin#278]
# 只在开发模式中被载入
VITE_PORT = 8082

# 网站根目录
VITE_PUBLIC_PATH = /

# 是否开启mock
VITE_USE_MOCK = false

# 网站前缀
VITE_BASE_URL = /

# 是否删除console
VITE_DROP_CONSOLE = true

# 跨域代理，可以配置多个，请注意不要换行
VITE_PROXY = [["/api","http://localhost:8080"]]
#VITE_PROXY = [["/api","http://localhost:8080"]]

# API 接口地址
VITE_GLOB_API_URL =/api

# 图片上传地址
VITE_GLOB_UPLOAD_URL=

# 图片前缀地址
VITE_GLOB_IMG_URL=

# 接口前缀
VITE_GLOB_API_URL_PREFIX =
![image](https://github.com/jekip/naive-ui-admin/assets/29847018/be841e49-c015-4183-b734-709db793dfff)
它请求还是走项目的端口地址？

**Comment by wilsunson** [comment]
VITE_GLOB_API_URL不能配，配了就代理不了咯
