### ISSUE TITLE
建议：全局Message和Dialog的实现方式

### ISSUE THREAD

**Issue by whitemay** [jekip/naive-ui-admin#29]
我注意到一个辅助的appProvider用于在程序初始化时将$message和$dialog注意到window对象中，便于供Axios使用。
但其实有更为方便的实现方式：使用mitt（实际已经引入未用到）。
mitt引入的对象同样是全局对象，并且listener可以延迟定义，定义在任何位置。

方法如下：首先定义一个全局bus对象（eventbus.ts）
```
import mitt from 'mitt';
export const bus = mitt();
```

在http中引入并使用该对象
```
import { bus } from '@/utils/eventbus';
...
bus.emit('error', 'error message');
bus.emit('modal', { 
    msg: 'anything to show',
    ...
});
```

在引入NMessageProvider和NDialogProvider后的任何地方（例如MessageContent.vue中）监听事件：
```
import { bus } from '@/utils/eventbus';
...
const Message = useMessage();
bus.on('error', (msg: string) => Message.error(msg));
bus.on('modal', (e: any) => ...);
```

这样就可以去掉window注入、appProvider等附加机制，逻辑上更为清晰。
以上思路供参考。

**Comment by jekip** [comment]
如果只是为了去掉window注入，您所说的这个方式，确实可行。

appProvider重点是里面的，***-provider组件模板，UI框架需要挂载在app.vue之前渲染，才可调用，并且 useMessage也只能在setup中引入，不得已才在window注入。

另外近期我在规划v2大版本，如果你尝试了比较好的方式可以pr一波，最终都会合并在v2版本中，感谢！

**Comment by whitemay** [comment]
各种provider本来就是在靠近dom root的位置。按照你现在的设计，其实不需要另行提前加载一个独立的AppProvider，也基本可以正常工作。
我大致浏览过代码，没有发现除了Axios外使用useMessage的情况。

我想这里的问题实际是：
- UI构成之前，是否会有预触发的网络请求；
- 相关的信息，既然UI还未构成，如何能够正常显示。

采用mitt方案的目的，实际上是让事件的产生和处理过程解耦，不是通过互相依赖，而是通过配置过程连接起来。这样useMessage可以在**-provider后的任何一个子组件的setup中使用，通过mitt和错误信息的处理关联起来。
这样最糟的情况无非是引入useMessage之前的消息会被抛弃掉，但之后的消息都会被正常处理。

实际我认为并不会有消息被抛弃掉。这里的考虑是：
- UI构成之前，用户交互有实际意义吗？

我觉得可能比较理想的构造方式是：
- MessageProvider和DialogProvider放到App.vue里面，AppProvider之外；
- 在AppProvider的setup里面引入useMessage、useDialog和mitt来完成事件的监听、错误消息显示。
- 然后子级StoreProvider被触发，layout、RouteView构造。而此时mitt和axios拦截器已经完成耦合，可以正常显示。

**Comment by jekip** [comment]
UI构成之前，确实会有请求，比如路由钩子中；
提前加载一个独立的AppProvider，是为了路由钩子中，实现 Loading Bar；
感谢您提的建议，如果可行那真是皆大欢喜；
另外，可以来qq群328347666，方便沟通。

**Comment by whitemay** [comment]
还有另外一个重要考虑：根据vue的最佳实践的要求，controller代码不应该试图直接操作UI。应该准备好数据，由ui来决定如何展示。

axios调用是典型的controller代码，message报错也是ui。绕过系统限制，在拦截器里调useMessage是不符合最佳实践的。这可能也是你构造起来别扭的原因。

即使不用mitt，也最好是用类似的方式，将数据保存在某个store中，由ui在空闲的时候主动展示。

**Comment by jekip** [comment]
是的，迫不得已才这样干的，如果是antd ui框架，可能没这个问题，naiveui 的 Message 和 Dialog 提示类的组件，都是依赖app和模板，还有Loading Bar，为了追求框架组件使用完整性，废弃了nprogress

我描述一个场景：当用户信息过期了，如果此时刷新页面，首先就会进入路由钩子函数中，触发请求，拦截跳转，此时app setup中代码起不到作用（类似的还有一些）

**Comment by whitemay** [comment]
这样吧，我fork出去改一版，按照我说的这个思路，把Loading Bar也加进来。然后你可以试试看。

**Comment by whitemay** [comment]
改完了，你可以试试看。
一般性的加载没有问题，你举的那个信息过期的例子，我没能触发成功，所以还不清楚那边有没有bug。
https://github.com/whitemay/naive-ui-admin

**Comment by jekip** [comment]
你是不是没提交，https://github.com/whitemay/naive-ui-admin 代码没变化？

**Comment by whitemay** [comment]
确实，现在提交了。
