### ISSUE TITLE
BasicTable分页和选择其他分页数，BasicForm选择和填入的参数丢失

### ISSUE THREAD

**Issue by tanwenchao** [jekip/naive-ui-admin#292]
<img width="446" alt="image" src="https://github.com/jekip/naive-ui-admin/assets/17673324/0f5c2028-8053-418f-bbae-26381788d108">
reload方法中未获取BasicForm的参数

**Comment by jekip** [comment]
BasicForm 的参数 需要手动注入，可以参考基础列表示例
