### ISSUE TITLE
🐱‍🏍🐱‍🏍🐱‍🏍真诚邀请您使用alova

### ISSUE THREAD

**Issue by JOU-amjs** [jekip/naive-ui-admin#295]
您好，我是alovajs的作者胡镇。

仔细看了您写的naive-ui-admin非常不错，然后我发现项目中使用的是axios，虽然做了一些请求层封装，但使用方式还较为传统，所以尝试邀请您使用alova+axios，我们也会在alova官网推荐您的项目，不知道您有没兴趣，我简单介绍一下。

[alova文档](https://alova.js.org)

alova定位为下一代请求工具，它的场景化请求策略和更先进的openAPI方案，可以极致简化您项目的api调用，具体推荐您看下[alova简介](https://alova.js.org/tutorial/getting-started/introduce)，您的收益和成本大概是这样的：

收益：alova提供了15+个场景化的请求策略，以及响应缓存和请求共享等高级特性，后台管理多以列表和表单为主，alova的分页策略和表单提交策略都可以让你的项目使用者快速实现完整的列表和表单功能，配合openAPI还可以获得极致的API集成效率。
成本：我仔细看过naive-ui-admin源码，可以通过重写`@/utils/http`模块快速迁移，把createAxios函数内改成返回alova的method实例，调用那边与现在保持一致就可以，什么都不用动，因为alova的传参和axios保持了一致，然后也然后是100%适配axios的，你可以用到axios的所有功能。

这些应该会让您的项目增添一点色彩，要是有意向迁移的话，我会提供全力的支持，不知道您意下如何？可以随时通过微信号“alova_js”联系我哦！

**Comment by jekip** [comment]
非常感谢，`alovajs` 作者的邀请，`alovajs` 库非常不错，其实我一直有意尝试使用，并迁移到 `alova` ，只是这个开源项目迟迟未行动，如您有时间，可以适当花点时间帮我贡献一个 最佳实战 `pr`，我和社区的小伙伴，都会非常感谢您的付出！

**Comment by JOU-amjs** [comment]
可以的，我近几天安排来一个pr。

对了，老哥，这位是你吧，现在才发现你是naive-ui-admin的作者😅
![image](https://github.com/user-attachments/assets/898c9135-1bff-4991-b1c3-5a670efa0e48)

**Comment by jekip** [comment]
是的，嘿嘿

**Comment by JOU-amjs** [comment]
这是我在alova的issue中选的，没想到在这遇到你了，有缘！

**Comment by jekip** [comment]
感谢您，无形中帮我推广了一波、哈哈~

**Comment by JOU-amjs** [comment]
😎下次可以改成“alovajs很不错。已在naive-ui-admin集成” 了

**Comment by jekip** [comment]
`2.0.0` 版本，已初步切换到 `alovajs` 不过最佳实战和示例并未完善 ~
