### ISSUE TITLE
此项目是基于Vite的如何用VTU（vue test utils）进行单元测试

### ISSUE THREAD

**Issue by ztw2010** [jekip/naive-ui-admin#32]
最近要对项目加入VTU和jest进行单元测试，发现babel不支持import.meta.env，想请教下作者这个项目怎么用VTU做单元测试的

**Comment by jekip** [comment]
我对单元测试这块，确实不擅长，本项目也没涉及这个，import.meta.env 是vite独有的语法，只能说你可以尝试以下方法看看
1、尝试配置babel的presets让它支持es6的语法，在项目的根目录下新建一个.babelrc的文件,内容如下：
`{
  "presets": [["@babel/preset-env", { "targets": { "node": "current" } }]]
}`
2、根目录中配置`jest.config.js`
`module.exports = {
    // 转义
    transform: {
      '^.+\\.vue$': 'vue-jest',
      '^.+\\js$': 'babel-jest',
      "^.+\\.(t|j)sx?$": "ts-jest"
    },
    moduleFileExtensions: ['vue', 'js', 'json', 'jsx', 'ts', 'tsx', 'node']
}`

**Comment by ztw2010** [comment]
菲常感谢作者的回复，这些配置我都尝试过了，最后是jest不支持import.meta.env语法，具体见https://github.com/vitejs/vite/issues/1955 。这样的话Vite创建的工程都不能进行单元测试了，感觉很遗憾



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ah ***@***.***&gt;; 
发送时间: 2021年8月18日(星期三) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jekip/naive-ui-admin] 此项目是基于Vite的如何用VTU（vue test utils）进行单元测试 (#32)





 
我对单元测试这块，确实不擅长，本项目也没涉及这个，import.meta.env 是vite独有的语法，只能说你可以尝试以下方法看看
 1、尝试配置babel的presets让它支持es6的语法，在项目的根目录下新建一个.babelrc的文件,内容如下：
 { "presets": ***@***.***/preset-env", { "targets": { "node": "current" } }]] }
 2、根目录中配置jest.config.js
 module.exports = { // 转义 transform: { '^.+\\.vue$': 'vue-jest', '^.+\\js$': 'babel-jest', "^.+\\.(t|j)sx?$": "ts-jest" }, moduleFileExtensions: ['vue', 'js', 'json', 'jsx', 'ts', 'tsx', 'node'] }
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
