### ISSUE TITLE
建议：菜单权限

### ISSUE THREAD

**Issue by czm-523** [jekip/naive-ui-admin#37]
菜单配置建议全部在前端设置，比如路径，component等，这个东西基本后端不会有改动的，后端系统只是负责菜单的分配，菜单使用编号来标识，前后端统一，后端只是返回改用户的菜单id就可以知道该客户的菜单列表，我的意思是权限只是控制到菜单。
望采纳

**Comment by jekip** [comment]
目前项目提供3种权限。
看你上面描述，第3种权限就是你所说的方案，菜单自行约定编号由后端接口下发，前端固定路由菜单和后端一 一对应，最终渲染页面达到权限控制目的
