### ISSUE TITLE
permission.ts 自定义指令在dom实例化完成后再视情况remove的逻辑有点问题

### ISSUE THREAD

**Issue by felismargarita** [jekip/naive-ui-admin#44]
dom已经挂载,此时即便remove了,也会导致created生命周期被触发,建议还是通过v-if实现,或者实现一个Access组件实现更加细致的控制

**Comment by jekip** [comment]
- 指令一般用于，单纯按钮判断显示或者移除

- 其余的判断如果需要用到，v-if 判断，可使用，hooks usePermission方法实现

**Comment by felismargarita** [comment]
> * 指令一般用于，单纯按钮判断显示或者移除
> * 其余的判断如果需要用到，v-if 判断，可使用，hooks usePermission方法实现

* 按钮组件也不排除created生命周期内做了一些操作,这不冲突,这个指令的缺陷就是created生命周期势必是执行了.
