### ISSUE TITLE
useForm通过getFieldsValue获取值问题

### ISSUE THREAD

**Issue by yanbowe** [jekip/naive-ui-admin#49]
场景：官方示例弹窗扩展页面中。
复现步骤：填写姓名， 点击弹窗确定按钮，通过useForm暴露的getFieldsValue方法只能获取到用户手动录入的值，无法获取到已经设置的默认值， 例如弹窗扩展里面的预约时间不主动触发的话是无法通过getFieldsValue获取到该值得

期望：通过defaultValue设置默认值，不触发一样可以拿到值

**Comment by yanbowe** [comment]
补充：通过getFieldsValue拿到的不是整个Form表单对象，而是用户触发过的字段才通过getFieldsValue返回出来

**Comment by jekip** [comment]
示例我也写错了，正确是defaultValue写到 schema 里面，而不是 schema.componentProps里面，测试了一下，正常返回
