### ISSUE TITLE
表格列设置优化

### ISSUE THREAD

**Issue by yanbowe** [jekip/naive-ui-admin#52]
![image](https://user-images.githubusercontent.com/43030980/133563847-dceb6a4a-4451-4ad0-9566-76fa589453d1.png)
表格列设置，在数据量50条及以上的时候会有2秒左右的卡顿

**Comment by yanbowe** [comment]
勾选以及拖拽列的时候卡顿明显

**Comment by jekip** [comment]
v2尝试优化了（发现二次封装代码运行并不慢），慢的原因是table组件内部渲染慢了
