### ISSUE TITLE
有计划支持分栏布局吗

### ISSUE THREAD

**Issue by qingmang** [jekip/naive-ui-admin#57]
![image](https://user-images.githubusercontent.com/67047984/135205736-f367fbc6-a7b0-4871-bb9a-595d4eafbda7.png)

类似这种的菜单布局

**Comment by jekip** [comment]
v2可能会做，优先级不是很高

**Comment by qingmang** [comment]
> v2可能会做，优先级不是很高

V2是收费的吗

**Comment by jekip** [comment]
可以关注一下，官网 https://www.naiveadmin.com
