### ISSUE TITLE
antd版的Table里面的TableAction是否可以支持antd的原颜色

### ISSUE THREAD

**Issue by san346596324** [jekip/naive-ui-admin#69]
![RCSULRI%O} BAOWL3ZD K_D](https://user-images.githubusercontent.com/30828520/142091532-d005c6c1-baf4-4178-b10b-55c51cebfcb7.png)
1.antd版的Table里面的TableAction是否可以支持antd的原颜色
2.使用danger的时候，按钮颜色可以不变淡色吗

**Comment by jekip** [comment]
排查了一下，这个是 `antd` 样式本身问题，等后续版本看一下，是否修复
在 `2.2.0` 之后，危险成为一种按钮属性而不是按钮类型，可能和这里有关，`3.x` 目前确实存在这个问题
