### ISSUE TITLE
完善ts类型检测

### ISSUE THREAD

**Issue by xiaojia21190** [jekip/naive-ui-admin#7]
![image](https://user-images.githubusercontent.com/16084693/126854522-ac3c5c1e-fee8-4ed4-89b3-5643a4e3d3e1.png)
![image](https://user-images.githubusercontent.com/16084693/126854532-044ac6a5-1d32-40b8-a96b-c3214dabcc6e.png)

**Comment by jekip** [comment]
ts类型检测确实写的不全，感谢反馈，已慢慢优化
