### ISSUE TITLE
antd版的 BasicTable 插槽应该有bug

### ISSUE THREAD

**Issue by san346596324** [jekip/naive-ui-admin#71]
![1637373586(1)](https://user-images.githubusercontent.com/30828520/142710579-dffece87-bdb5-445e-833f-eca7c3df7634.jpg)
![1637373623(1)](https://user-images.githubusercontent.com/30828520/142710583-d1441ca9-83df-46a7-960c-37497029cafc.jpg)
![1637373641(1)](https://user-images.githubusercontent.com/30828520/142710586-78011796-eef4-4cb3-a1dc-354aa1d4a1f3.jpg)

**Comment by jekip** [comment]
参考，antd 3.x 最新写法
