### ISSUE TITLE
看了下官网说明，请问V1版本又开源免费了？

### ISSUE THREAD

**Issue by WongLeee** [jekip/naive-ui-admin#72]
![image](https://user-images.githubusercontent.com/30207832/144014794-eb7589a6-6f6c-4c1a-810f-a235232471dd.png)

**Comment by jekip** [comment]
1.x 一直都是开源的免费的，最近问的人比较多，决定声明一下

**Comment by WongLeee** [comment]
好的，谢谢大佬解惑
