### ISSUE TITLE
开发模式下每间隔几秒就会自动刷新

### ISSUE THREAD

**Issue by 272916173** [jekip/naive-ui-admin#75]
v1的版本，我用yarn dev跑起来之后无论是哪一个页面都会间隔几秒就全页面刷新一次，请问这个可以在哪里改一下吗

**Comment by jekip** [comment]
开发模式下，首次启动，确实出现过这种情况，不过只是偶现，可以跟踪一下，具体啥原因，这个或许和 `vite` 有关，可以尝试升级到最新版本

**Comment by 272916173** [comment]
> 


![image](https://user-images.githubusercontent.com/2511608/145766810-e523e29d-b0dc-4db7-836e-3ad8cff14208.png)

感谢大大回复，我找到原因应该是因为我是部署在服务器上，然后用nginx做了一个反向代理，但是页面有ws连接8001端口，连不上就重试刷新了。。。
请问这个项目里面websocket这个作用是什么呢，可以关闭吗，或者我可以在哪里改成nginx的端口呢，大概翻了下代码没找到在哪里，感谢。

**Comment by jekip** [comment]
项目示例，并没有用到  `websocket` ，虽然不知道你问题所在，不过你可以把前端服务换一个端口试试，在根目录，`.env.development` 文件中 `VITE_PORT` 字段，另外您是前端开启代理，然后打包之后，部署在服务器，出现的问题吗？

**Comment by 272916173** [comment]
我没有打包，是直接yarn dev以开发模式运行在服务器上，因为那个服务器上只开放了外网的80和443端口，以及还有很多别的东西跑着，就统一用nginx做了不同的代理转发。

**Comment by jekip** [comment]
建议打包在部署，dev只是在开发模式下使用，直接部署这个也不太合适，服务器有很多外在因素，会导致很多问题存在

**Comment by 272916173** [comment]
好的，谢谢解答了。

**Comment by 272916173** [comment]
我找到了解决办法了，想想还是发出来给万一跟我一样有远程开发需求的人参考
node_modules/vite/src/client/client.ts这个文件找到下面的内容：
// ping server
socket.addEventListener('close', async ({ wasClean }) => {
  if (wasClean) return
  console.log(`[vite] server connection lost. polling for restart...`)
  await waitForSuccessfulPing()
  **location.reload()**
})

注释掉加粗的这一行就行了
