### ISSUE TITLE
兄弟，自己骗自己有意思吗

### ISSUE THREAD

**Issue by acegank** [jekip/naive-ui-admin#76]
你这套系统源码根本就是从vben那拿来自己阉割，看看vben的功能，关键你这个还收费授权，实在是过分

**Comment by jekip** [comment]
首先 1.x 是开源免费的，里面的确借鉴了 vben 的代码，收费授权是 2.x 版本，开源还是收费，都是每个开发者的自由，为何你作为程序员，你既然觉得这很过分，我有点怀疑，你不是程序员，哈哈~

在你看来我是自己骗自己，在我看来，你这种行为，才是自己骗自己，你在这里发布言论，难道别人就不会觉得你很过分吗？

都是成年人了，别说这些，无关紧要，还鸡毛蒜皮的事了，早点睡吧~

**Comment by acegank** [comment]
本来你抄就抄，代码反正都是抄，我也无所谓，但你收费就是过分。2.x还敢说不是抄的。看看你的源码吧，你要是自己写的当然有权利决定收费与否，问题是你是抄袭者。成年人了，要点脸。我只是看不过，在你这陈述一个事实而已。抄就抄，不要拿抄的东西来说自己的还要收钱。
