### ISSUE TITLE
站点错字

### ISSUE THREAD

**Issue by YangFong** [jekip/naive-ui-admin#77]
我注意到站点的部分内容有些不对劲，在我的角度，要么是 `antd`，要么是 Antd

![image](https://user-images.githubusercontent.com/70502828/146472689-c4326a6d-34b0-4d37-9905-6094a2d7b85f.png)

**Comment by jekip** [comment]
确实，存在这个问题，准确一点应该叫，`Ant Vue` 或者 `Ant Design Vue` ，我 `fix` 一下

**Comment by jekip** [comment]
感谢，反馈，已修正
