### ISSUE TITLE
naive ant分页报错

### ISSUE THREAD

**Issue by san346596324** [jekip/naive-ui-admin#79]
![1640441178(1)](https://user-images.githubusercontent.com/30828520/147386774-d30825a7-f113-4e6a-ad84-e1430e0112cb.jpg)
![1640441191(1)](https://user-images.githubusercontent.com/30828520/147386776-9982ab7e-cc5f-49ab-9191-880a3cba1e45.jpg)

**Comment by jekip** [comment]
已修复
