### ISSUE TITLE
Message的先后顺序

### ISSUE THREAD

**Issue by Garens** [jekip/naive-ui-admin#8]
在axios中，作者使用了
`const { $dialog: Modal, $message: Message } = window;`
但是window的Message赋值，是在Application组件中使用，Application组件又是在App.vue中才调用，导致Message对象，在没有进入到App.vue时候（也就比如在登录界面中就触发调用）就不生效。

**Comment by jekip** [comment]
登录页渲染完了app也完了，应该是可以用才对。
目前这种写法缺点：
1、路由拦截器里面无法使用
2、举例子，当登录信息失效了，手动刷新页面那一刻，如果路由拦截器种有axios请求，触发了错误信息，$dialog 这个也是用不了

**Comment by Garens** [comment]
是的，是否可以解决这个问题呢？还有，axios里面，用到的Modal.confirm，但是对应的naive UI 中没有这个方法了

**Comment by jekip** [comment]
社区有一个例子，我看了，没尝试过，不知道是否真正解决了此问题，你有兴趣可以试下，https://github.com/Talljack/naive-ui-provider/tree/main/src 

Modal.confirm 用  Modal.info 代替了，之前的，Modal.confirm 写法也有问题，今天已修正，明天会更新一个版本

最后，还是要感谢使用和反馈！

**Comment by jekip** [comment]
已解决，升级1.5
