### ISSUE TITLE
路由在切换的时候出现空白

### ISSUE THREAD

**Issue by louisqing** [jekip/naive-ui-admin#85]
路由切换的时候出现空白
![image](https://user-images.githubusercontent.com/21032223/149290170-672ad06d-4631-49c9-b21a-7d85f6670670.png)

**Comment by louisqing** [comment]
template 标签请记得用div包一层，新版的vue3.0是可以不包的。但是不包也不会提示任何错误，只有路由出不来

**Comment by jekip** [comment]
这是因为框架，使用了过滤动画组件，那个组件不支持多个根元素，所以会这样

**Comment by qingmang** [comment]
我觉得可以废弃这个过滤动画 跟vue3写法冲突不是长久之计

**Comment by qingmang** [comment]
@jekip

**Comment by qingmang** [comment]
我调试了半天 知道看到这个issue

**Comment by likailun101929** [comment]
请问解决了  怎么解决的 我偶尔还是会遇到
