### ISSUE TITLE
BasicTable组件配置:pagination="{ pageSize: 20 }" 之后， pageSizes 切换页数量，依然是 20

### ISSUE THREAD

**Issue by xingxian1982** [jekip/naive-ui-admin#86]
<BasicTable
        :columns="columns"
        :request="loadDataTable"
        :row-key="(row) => row.id"
        ref="actionRef"
        :pagination="{pageSize:20}"
        :actionColumn="actionColumn"
        @update:checked-row-keys="onCheckedRow"
      >
配置:pagination="{ pageSize: 20 }" 之后
分页这里修改不再生效
![Uploading i2.png…]()

**Comment by jekip** [comment]
已修复
