### ISSUE TITLE
页面上有锚点的时间，点击锚点都是打开一个新页面，只不过标签没换

### ISSUE THREAD

**Issue by xingxian1982** [jekip/naive-ui-admin#87]
<n-anchor
          affix
          listen-to=".n-layout-page-header"
          :trigger-top="140"
          style="z-index: 1"
          :bound="24"
        >
          <n-anchor-link title="基础用法" href="#basic" />
          <n-anchor-link title="预约备注" href="#remark" />
</n-anchor>

...
<n-input v-model:value="formValue.name" placeholder="输入姓名" />
...
初始页面路径：/form/basicForm , name填 1
在vue页面上加上锚点后，点击锚点跳转路径：/form/basicForm#basic
虽然页签没有改变，但是页面之前输入的内容都不见了，重新输入name填 2，
后再点击#remark，跳转到/form/basicForm#remark，输入的内容又不见了，再重新输入name填 3

然后发现：
/form/basicForm#basic 里 name=2
/form/basicForm#remark 里name=3
两个锚点展示出来的页面上各自有自己的内容，感觉在路由里面还是三个页面，只不过标签没变

**Comment by jekip** [comment]
暂时没有比较好的解决方案 `createWebHistory` 模式，当使用不同锚点的时候，确实是生成了多个路由堆栈，锚点功能是不受影响的，只是需要配合 `keep-alive ` 确实不是那么完美
