### ISSUE TITLE
后端技术要怎样应用这个库？

### ISSUE THREAD

**Issue by shaukei** [jekip/naive-ui-admin#90]
对前端技术不是很熟悉的后端，怎样快速上手这套ui？

**Comment by shaukei** [comment]
是通过api来交互数据？页面切换是通过前端框架来实现？

**Comment by jekip** [comment]
1、这是前端整套解决方案，后端只需写好`api`即可，适合前后端分离，技术架构
2、后端上手也简单，配合项目文档，只需把`api`，按照`mock`中`json`格式，返回数据结构，即可
3、可以加入qq群，交流讨论，里面很多后端小伙伴，也用得很不错
