### ISSUE TITLE
这个验证码对网络的要求好像比较高，一直加载不出来。

### ISSUE THREAD

**Issue by 332lfgb6** [jekip/naive-ui-admin#94]
![图片](https://user-images.githubusercontent.com/51245335/152480016-57f91d51-1fa4-4fdf-b2c0-6e923078c1a4.png)

**Comment by jekip** [comment]
确实，这个是第三方的，不推荐使用，本项目只是为了演示

**Comment by zhou-tao** [comment]
> 确实，这个是第三方的，不推荐使用，本项目只是为了演示

但是加载不出来的话登录进不去了。。

**Comment by zhou-tao** [comment]
好像是验证码图片地址域名证书过期

**Comment by jekip** [comment]
由于不稳定等问题，`1.7.0` 已移除，这个第三方验证组件库
