### ISSUE TITLE
暗黑模式下侧边栏Menu和Switch组件主题色切换失效

### ISSUE THREAD

**Issue by Qujh97** [jekip/naive-ui-admin#95]
![QQ截图20220207134147](https://user-images.githubusercontent.com/33251372/152731129-deb99788-cab0-473a-bdc5-79f140c98ef6.jpg)

Swtich组件颜色可以通过`n-config-provider` `theme-overrides`覆盖主题解决
```
{
    // worked
    Switch: {
      railColorActive: appTheme,
      loadingColor: appTheme,
    }
}
```
针对Menu做了类似的处理，没有奏效
```
{
    // didn't work
    Menu: {
      itemColorActive: appTheme,
      itemColorActiveCollapsed: appTheme,
    },
}
```

**Comment by jekip** [comment]
配置 `common.primaryColorSuppl` 试试

**Comment by Qujh97** [comment]
> 配置 `common.primaryColorSuppl` 试试

可以了，感谢
